<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NotificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('notification_templates')->insert([
            [
                'id' => 1,
                'language_id' => 1,
                'name' => 'Profile update',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'PROFILE_UPDATE',
                'subject' => 'Admin Profile Update',
                'short_keys' => '{"sender":"Sender Name","amount":"Received Amount","currency":"Transfer Currency","transaction":"Transaction Number"}',
                'email' => 'Your profile has been updated',
                'sms' => 'Your profile has been updated',
                'in_app' => 'Your profile has been updated',
                'push' => 'Your profile has been updated',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2021-08-02 12:05:43',
                'updated_at' => '2023-10-21 21:54:01',
            ],
            [
                'id' => 2,
                'language_id' => 1,
                'name' => 'Profile Update',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'PROFILE_UPDATE',
                'subject' => 'User Profile Update',
                'short_keys' => '{"sender":"Sender Name","amount":"Received Amount","currency":"Transfer Currency","transaction":"Transaction Number"}',
                'email' => 'Your profile has been updated',
                'sms' => 'Your profile has been updated',
                'in_app' => 'Your profile has been updated',
                'push' => 'Your profile has been updated',
                'notify_for' => 0,
                'status' => '{"mail":"0","sms":"1","in_app":"0","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 03:26:59',
                'updated_at' => '2023-10-19 04:07:40',
            ],

            [
                'id' => 3,
                'language_id' => 1,
                'name' => 'Balance credited by Admin',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'ADD_BALANCE',
                'subject' => 'Your Account has been credited',
                'short_keys' => '{"transaction":"Transaction Number","amount":"Request Amount By Admin","main_balance":"Users Balance After this operation"}',
                'email' => '[[amount]] credited in your account. \n\n\nYour Current Balance [[main_balance]]\n\nTransaction: #[[transaction]]',
                'sms' => '[[amount]] credited in your account. \n\n\nYour Current Balance [[main_balance]]\n\nTransaction: #[[transaction]]',
                'in_app' => '[[amount]] credited in your account. \n\n\nYour Current Balance [[main_balance]]\n\nTransaction: #[[transaction]]',
                'push' => '[[amount]] credited in your account. \n\n\nYour Current Balance [[main_balance]]\n\nTransaction: #[[transaction]]',
                'notify_for' => 0,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 4,
                'language_id' => 1,
                'name' => 'Balance deducted by Admin',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'DEDUCTED_BALANCE',
                'subject' => 'Your Account has been debited',
                'short_keys' => '{"transaction":"Transaction Number","amount":"Request Amount By Admin","main_balance":"Users Balance After this operation"}',
                'email' => '[[amount]] debited in your account.\n\nYour Current Balance [[main_balance]]\n\nTransaction: #[[transaction]]',
                'sms' => '[[amount]] debited in your account.\n\nYour Current Balance [[main_balance]]\n\nTransaction: #[[transaction]]',
                'in_app' => '[[amount]] debited in your account.\n\nYour Current Balance [[main_balance]]\n\nTransaction: #[[transaction]]',
                'push' => '[[amount]] debited in your account.\n\nYour Current Balance [[main_balance]]\n\nTransaction: #[[transaction]]',
                'notify_for' => 0,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 5,
                'language_id' => 1,
                'name' => 'Support Ticket Create',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'SUPPORT_TICKET_CREATE',
                'subject' => 'New Support Ticket',
                'short_keys' => '{"ticket_id":"Support Ticket ID","username":"username"}',
                'email' => '[[username]] replied  ticket\nTicket : [[ticket_id]]',
                'sms' => '[[sender]] send money to your account amount [[amount]] [[currency]] . Transaction: #[[transaction]]',
                'in_app' => '[[username]] create a ticket\nTicket : [[ticket_id]]',
                'push' => '[[username]] create a ticket\nTicket : [[ticket_id]]\n\n',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2021-08-02 12:05:43',
                'updated_at' => '2023-10-08 03:15:37',
            ],
            [
                'id' => 6,
                'language_id' => 1,
                'name' => 'Admin Replied Ticket',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'ADMIN_REPLIED_TICKET',
                'subject' => 'Admin Replied Ticket',
                'short_keys' => '{"ticket_id":"Support Ticket ID"}',
                'email' => 'Admin replied  ticket\nTicket : [[ticket_id]]',
                'sms' => 'Admin replied  ticket\nTicket : [[ticket_id]]',
                'in_app' => 'Admin replied  ticket\nTicket : [[ticket_id]]',
                'push' => 'Admin replied  ticket\nTicket : [[ticket_id]]',
                'notify_for' => 0,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 7,
                'language_id' => 1,
                'name' => 'KYC Approval',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'KYC_APPROVED',
                'subject' => 'User KYC Approval',
                'short_keys' => '...',
                'email' => 'Your KYC has been approved',
                'sms' => 'Your KYC has been approved',
                'in_app' => 'Your KYC has been approved',
                'push' => 'Your KYC has been approved',
                'notify_for' => 0,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 8,
                'language_id' => 1,
                'name' => 'KYC Rejection',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'KYC_REJECTED',
                'subject' => 'User KYC Rejection',
                'short_keys' => 'Your KYC has been rejected',
                'email' => 'Your KYC has been rejected',
                'sms' => 'Your KYC has been rejected',
                'in_app' => 'Your KYC has been rejected',
                'push' => 'Your KYC has been rejected',
                'notify_for' => 0,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],


            [
                'id' => 9,
                'language_id' => 1,
                'name' => 'Payment Request',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'PAYMENT_REQUEST',
                'subject' => 'Payment Request',
                'short_keys' => '{"gateway":"gateway","currency":"currency","username":"username"}',
                'email' => '[[username]] deposit request [[amount]] via [[gateway]]',
                'sms' => '[[username]] deposit request [[amount]] via [[gateway]]',
                'in_app' => '[[username]] deposit request [[amount]] via [[gateway]]',
                'push' => '[[username]] deposit request [[amount]] via [[gateway]]',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 10,
                'language_id' => 1,
                'name' => 'Payment Approval',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'PAYMENT_APPROVED',
                'subject' => 'Payment Approval',
                'short_keys' => '{"amount":"amount", "transaction":"transaction","feedback":"Admin feedback"}',
                'email' => 'Your payment request has been approved \nTransaction: #[[transaction]]\nAmount: [[amount]]',
                'sms' => 'Your payment request has been approved \nTransaction: #[[transaction]]\nAmount: [[amount]]',
                'in_app' => 'Your payment request has been approved \nTransaction: #[[transaction]]\nAmount: [[amount]]',
                'push' => 'Your payment request has been approved \nTransaction: #[[transaction]]\nAmount: [[amount]]',
                'notify_for' => 0,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 11,
                'language_id' => 1,
                'name' => 'Payment Rejection',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'PAYMENT_REJECTED',
                'subject' => 'Payment Rejected',
                'short_keys' => '{"amount":"amount","gateway":"gateway","transaction":"transaction","feedback":"Admin feedback"}',
                'email' => 'Your payment request has been rejected \nTransaction: #[[transaction]]\nAmount: [[amount]]',
                'sms' => 'Your payment request has been rejected \nTransaction: #[[transaction]]\nAmount: [[amount]]',
                'in_app' => 'Your payment request has been rejected \nTransaction: #[[transaction]]\nAmount: [[amount]]',
                'push' => 'Your payment request has been rejected \nTransaction: #[[transaction]]\nAmount: [[amount]]',
                'notify_for' => 0,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 12,
                'language_id' => 1,
                'name' => 'Deposit',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'ADD_FUND_USER_USER',
                'subject' => 'Add Fund User',
                'short_keys' => '{"amount":"Request Amount","transaction":"Transaction Number"}',
                'email' => 'You have deposited money amount [[amount]] [[currency]]. Transaction: #[[transaction]]',
                'sms' => 'You have deposited money amount [[amount]] [[currency]]. Transaction: #[[transaction]]',
                'in_app' => 'You have deposited money amount [[amount]] [[currency]]. Transaction: #[[transaction]]',
                'push' => 'You have deposited money amount [[amount]] [[currency]]. Transaction: #[[transaction]]',
                'notify_for' => 0,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 13,
                'language_id' => 1,
                'name' => 'Add Fund User Admin',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'ADD_FUND_USER_ADMIN',
                'subject' => 'Add Fund User Admin',
                'short_keys' => '{"amount":"Request Amount","currency":"Request Currency","transaction":"Transaction Number","username":"username"}',
                'email' => '[[username]] has deposited money amount [[amount]] [[currency]]. Transaction: #[[transaction]]',
                'sms' => '[[username]] has deposited money amount [[amount]] [[currency]]. Transaction: #[[transaction]]',
                'in_app' => '[[username]] has deposited money amount [[amount]] [[currency]]. Transaction: #[[transaction]]',
                'push' => '[[username]] has deposited money amount [[amount]] [[currency]]. Transaction: #[[transaction]]',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],

            [
                'id' => 14,
                'language_id' => 1,
                'name' => 'Verification Code',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'VERIFICATION_CODE',
                'subject' => 'Verify Your Email',
                'short_keys' => '{"code":"code"}',
                'email' => 'Your Email verification Code [[code]]',
                'sms' => 'Your Email verification Code [[code]]',
                'in_app' => 'Your Email verification Code [[code]]',
                'push' => 'Your Email verification Code [[code]]',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 15,
                'language_id' => 1,
                'name' => 'Two Step Security Actions',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'TWO_STEP_ENABLED',
                'subject' => 'Two Step Security Actions',
                'short_keys' => '{"action":"action","code":"code","username":"username"}',
                'email' => 'Two Fa [[action]] by [[username]]',
                'sms' => 'Two Fa [[action]] by [[username]]',
                'in_app' => 'Two Fa [[action]] by [[username]]',
                'push' => 'Two Fa [[action]] by [[username]]',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],

            [
                'id' => 16,
                'language_id' => 1,
                'name' => 'Reset Password',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'PASSWORD_RESET',
                'subject' => 'Reset Password',
                'short_keys' => '{"message":"message"}',
                'email' => 'You are receiving this email because we received a password reset request for your account.[[message]]',
                'sms' => '',
                'in_app' => '',
                'push' => '',
                'notify_for' => 0,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],


            [
                'id' => 17,
                'language_id' => 1,
                'name' => 'Money Transfer Request Approve',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'TRANSFER_APPROVED',
                'subject' => 'Transfer Request Approved',
                'short_keys' => '{"amount":"Received Amount","currency":"Transfer Currency","transaction":"Transaction Number"}',
                'email' => 'You transfer request has been approved . Transaction: #[[transaction]]',
                'sms' => 'You transfer request has been approved . Transaction: #[[transaction]]',
                'in_app' => 'You transfer request has been approved . Transaction: #[[transaction]]',
                'push' => 'You transfer request has been approved . Transaction: #[[transaction]]',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 18,
                'language_id' => 1,
                'name' => 'Money Transfer Request Cancel',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'TRANSFER_CANCEL',
                'subject' => 'Transfer Request Cancel',
                'short_keys' => '{"amount":"Received Amount","currency":"Transfer Currency","transaction":"Transaction Number"}',
                'email' => 'Your Transfer request for amount [[amount]] [[currency]] has been canceled. Transaction: #[[transaction]]',
                'sms' => 'Your Transfer request for amount [[amount]] [[currency]] has been canceled. Transaction: #[[transaction]]',
                'in_app' => 'Your Transfer request for amount [[amount]] [[currency]] has been canceled. Transaction: #[[transaction]]',
                'push' => 'Your Transfer request for amount [[amount]] [[currency]]. Transaction: #[[transaction]]',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],


            [
                'id' => 25,
                'language_id' => 1,
                'name' => 'ADMIN VIRTUAL CARD APPLY',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'ADMIN_VIRTUAL_CARD_APPLY',
                'subject' => 'Virtual Card Applied',
                'short_keys' => '{"amount":"amount","currency":"currency","username":"username","transaction":"transaction"}',
                'email' => '[[username]] requested for a virtual card. Payment Amount [[amount]][[currency]].\r\nTransaction [[transaction]].',
                'sms' => '[[username]] requested for a virtual card. Payment Amount [[amount]][[currency]].\r\nTransaction [[transaction]].',
                'in_app' => '[[username]] requested for a virtual card. Payment Amount [[amount]] [[currency]].\nTransaction [[transaction]].',
                'push' => '[[username]] requested for a virtual card. Payment Amount [[amount]][[currency]].\r\nTransaction [[transaction]].',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],

            [
                'id' => 29,
                'language_id' => 1,
                'name' => 'Admin Panel Set Role',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'ADMIN_PANEL_SET_ROLE',
                'subject' => 'Set Role',
                'short_keys' => '{"role":"role","username":"username"}',
                'email' => '[[username]] new role is [[role]]\n',
                'sms' => '[[username]] new role is [[role]]\n',
                'in_app' => '[[username]] new role is [[role]]\n',
                'push' => '[[username]] new role is [[role]]\n',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 30,
                'language_id' => 1,
                'name' => 'Admin Panel Create New Admin',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'ADMIN_PANEL_CREATE_NEW_ADMIN',
                'subject' => 'Create New Admin',
                'short_keys' => '{"username":"username","password":"password"}',
                'email' => 'your account has been created. Here is your login credentials\nUsername: [[username]]\nPassword: [[password]]\n',
                'sms' => 'your account has been created. Here is your login credentials\nUsername: [[username]]\nPassword: [[password]]\n',
                'in_app' => 'your account has been created. Here is your login credentials\nUsername: [[username]]\nPassword: [[password]]\n',
                'push' => 'your account has been created. Here is your login credentials\nUsername: [[username]]\nPassword: [[password]]\n',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 31,
                'language_id' => 1,
                'name' => 'Virtual Card Block',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'VIRTUAL_CARD_BLOCK',
                'subject' => 'Virtual Card Block',
                'short_keys' => '{"amount":"amount","currency":"currency","username":"username"}',
                'email' => '[[username]] Virtual Card Block Amount [[amount]] [[currency]].\n',
                'sms' => '[[username]] Virtual Card Block Amount [[amount]] [[currency]].\n',
                'in_app' => '[[username]] Virtual Card Block Amount [[amount]] [[currency]].\n',
                'push' => '[[username]] Virtual Card Block Amount [[amount]] [[currency]].\n',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 32,
                'language_id' => 1,
                'name' => 'Virtual Card Unblock',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'VIRTUAL_CARD_UNBLOCK',
                'subject' => 'Virtual Card Unblock',
                'short_keys' => '{"amount":"amount","currency":"currency","username":"username"}',
                'email' => '[[username]] Virtual Card Unblock Amount [[amount]] [[currency]].\n',
                'sms' => '[[username]] Virtual Card Unblock Amount [[amount]] [[currency]].\n',
                'in_app' => '[[username]] Virtual Card Unblock Amount [[amount]] [[currency]].\n',
                'push' => '[[username]] Virtual Card Unblock Amount [[amount]] [[currency]].\n',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 33,
                'language_id' => 1,
                'name' => 'VIRTUAL CARD REQUEST',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'VIRTUAL_CARD_REQUEST',
                'subject' => 'Virtual Card Request',
                'short_keys' => '{"amount":"amount","currency":"currency","username":"username","transaction":"transaction"}',
                'email' => '[[username]] requested for a virtual card. Payment Amount [[amount]] [[currency]].\nTransaction [[transaction]].',
                'sms' => '[[username]] requested for a virtual card. Payment Amount [[amount]] [[currency]].\nTransaction [[transaction]].',
                'in_app' => '[[username]] requested for a virtual card. Payment Amount [[amount]] [[currency]].\nTransaction [[transaction]].',
                'push' => '[[username]] requested for a virtual card. Payment Amount [[amount]] [[currency]].\nTransaction [[transaction]].',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 34,
                'language_id' => 1,
                'name' => 'VIRTUAL CARD REJECT',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'VIRTUAL_CARD_REJECT',
                'subject' => 'Virtual Card Rejected',
                'short_keys' => '{"amount":"amount","currency":"currency","username":"username","transaction":"transaction"}',
                'email' => '[[username]] Virtual Card Rejected Amount [[amount]] [[currency]].\nTransaction [[transaction]].',
                'sms' => '[[username]] Virtual Card Rejected Amount [[amount]] [[currency]].\nTransaction [[transaction]].',
                'in_app' => '[[username]] Virtual Card Rejected Amount [[amount]] [[currency]].\nTransaction [[transaction]].',
                'push' => '[[username]] Virtual Card Rejected Amount [[amount]] [[currency]].\nTransaction [[transaction]].',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 37,
                'language_id' => 1,
                'name' => 'Kyc Approved',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'KYC_APPROVED',
                'subject' => 'Kyc Approved',
                'short_keys' => '{"username":"username"}',
                'email' => '[[username]] Kyc has been approved .\n',
                'sms' => '[[username]] Kyc has been approved .\n',
                'in_app' => '[[username]] Kyc has been approved .\n',
                'push' => '[[username]] Kyc has been approved .\n',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],
            [
                'id' => 38,
                'language_id' => 1,
                'name' => 'Kyc Rejected',
                'email_from' => 'bugfinder@gmail.com',
                'template_key' => 'KYC_REJECTED',
                'subject' => 'Kyc Rejected',
                'short_keys' => '{"username":"username"}',
                'email' => '[[username]] Kyc has been rejected .\n',
                'sms' => '[[username]] Kyc has been rejected .\n',
                'in_app' => '[[username]] Kyc has been rejected .\n',
                'push' => '[[username]] Kyc has been rejected .\n',
                'notify_for' => 1,
                'status' => '{"mail":"1","sms":"1","in_app":"1","push":"1"}',
                'lang_code' => 'en',
                'created_at' => '2023-10-07 22:18:47',
                'updated_at' => '2023-10-07 22:22:39',
            ],

        ]);
    }
}

