<?php

return [
    "Your Name",
    "Your Subject",
    "Your Message",
    "Send a massage",
    "countries",
    "Quick Links",
    "Support links",
    "Contact Us",
    "All rights reserved",
    "continue",
    "Transfer fee:",
    "IN Local:",
    "Select a currency",
    "Search here...",
    "Transfer Money",
    "Open an account",
    "You send exactly",
    "Receiver Amount  (Without Fee)",
    "Email Address",
    "Payment Failed",
    "We really appreciate you giving us a moment of your time today but unfortunately the payment was unsuccessful due to",
    "it seems some issue in server to server communication. Kindly connect with administrator",
    "Go Back to Home",
    "Redirecting in",
    "Payment Success",
    "Thanks a bunch for filling that out. It means a lot to us, just like you do! We really appreciate you giving us a moment of your time today. Thanks for being with us.",
    "Redirecting to home in",
    "Introduction Page",
    "Loading",
    "Coming Soon Content in",
    "If there is no content available in",
    "our administrators are working diligently to set up relevant content for our",
    "audience. We appreciate your patience as we strive to provide valuable information in your preferred language.",
    "Go To Settings",
    "Transfer Success",
    "Go to Dashboard",
    "Login",
    "Dashboard",
    "Explore our Blogs",
    "Home",
    "Contact",
    "Profile",
    "Previous",
    "Next",
    "Amount",
    "Recipient",
    "Review",
    "Pay",
    "Send-Money",
    "Recipients",
    "Card",
    "history",
    "Money Transfer",
    "Transactions",
    "Support Ticket",
    "Refer & Earn",
    "You have",
    "new notifications",
    "Clear all notification",
    "Sign Out",
    "More",
    "Accept",
    "Close",
    "see more",
    "Back to Homepage",
    "401 Unauthorized",
    "You are an unauthorized user",
    "403 Forbidden",
    "You don't have permission to access on this server",
    "We can't seem to find the page you are looking for",
    "Method Not Allowed",
    "Sorry, your session has expired",
    "The server encountered an internal error misconfiguration and was unable to complete your request. Please contact the server administrator.",
    "Confirm Password",
    "Please confirm your password before continuing.",
    "Password",
    "Forgot Your Password?",
    "Password Reset",
    "Forgot Your Password!",
    "Enter Your Email Address & Send Request for reset link",
    "Enter Your Email Address",
    "Send Password Reset Link",
    "Password Reset!",
    "Reset Password",
    "Enter New Password",
    "Enter Your Verification Code",
    "Code",
    "Submit",
    "Email Verification",
    "Your Email Address is",
    "Didn't get Code? Click to",
    "Resend code",
    "Send OTP",
    "Resend OTP",
    "SMS Verify",
    "we will send an otp in this number",
    "Email Verify",
    "we will send an otp in this email",
    "Both Email & SMS",
    "we sent an otp code to your email & sms both.",
    "Whats App",
    "we sent an otp code to your whats app number.",
    "Enter OTP",
    "submit",
    "We just sent you an SMS",
    "Enter the security code we sent",
    "Enter Your OTP Code",
    "Didn't get Code?",
    "Resend",
    "Try another way",
    "Username or Email",
    "Remember Me",
    "Log In",
    "Don't have an account?",
    "Create a Account",
    "Google",
    "Facebook",
    "Github",
    "Signup",
    "First Name",
    "Last Name",
    "username",
    "Email",
    "Sponsor Name",
    "Sponsor By",
    "password",
    "confirm password",
    "signup",
    "Already have an account?",
    "Login Here",
    "Verify Your Email Address",
    "Before proceeding, please check your email for a verification link",
    "click here to request another",
    "A fresh verification link has been sent to your email address.",
    "Do not miss any single important notification! Allow your browser to get instant push notification",
    "Allow me",
    "Please allow your browser to get instant push notification. Allow it from notification setting",
    "Transaction",
    "Latest Transactions",
    "See all",
    "Type",
    "Transaction ID",
    "Net Amount",
    "Base Amount",
    "Charge",
    "Time & Date",
    "Remarks",
    "action",
    "Sent",
    "Receive",
    "View Details",
    "No Data Found",
    "Create New Wallet",
    "wallet currency",
    "Create",
    "Deposit",
    "Your preferred payment method?",
    "Select Your Wallet",
    "Select Currency",
    "Enter Amount",
    "I agree to Terms & Conditions.",
    "Make Payment",
    "cancel this transfer",
    "Choose Currency",
    "Select a gateway first",
    "Select a Crypto Currency",
    "Pay To Crypto Currency",
    "Amount In",
    "Payable Amount",
    "Deposit History",
    "Back to Dashboard",
    "Filter",
    "Block Card",
    "All status",
    "Pending",
    "Success",
    "Requested",
    "Rejected",
    "Payment Information",
    "Payment method:",
    "Payment amount:",
    "Status:",
    "Summary",
    "Note",
    "Profile Settings",
    "Username",
    "Phone Number",
    "Preferred Language",
    "Select Language",
    "Address One",
    "Address Two",
    "Save Changes",
    "Cancel",
    "Choose Photo",
    "Allowed JPG, JPEG or PNG. Max size of 4M",
    "Settings",
    "Notifications",
    "Choose what we get in touch about",
    "SMS",
    "Push",
    "in App",
    "There are some things that we will always need to tell you about – like changes to our T&Cs.",
    "Change password",
    "warning",
    "Enter a strong password!",
    "Current password",
    "Your password",
    "Enter a new Password",
    "Confirm password",
    "Confirm Your Password",
    "Save",
    "2-step verification",
    "Manage your 2-step verification methods.",
    "Log out of all devices",
    "Logout from all devices",
    "If you notice any suspicious activity, log out of across all devices and browsers",
    "Hey :user, we're sorry to see you leave",
    "CONTINUE",
    "Hey :user, are you sure, you want to delete this account?",
    "No",
    "Yes",
    "Change Email Address",
    "Save changes",
    "Identity Verify",
    "KYC Information",
    "Verify your process instantly.",
    "Upload File",
    "Rejected Reason",
    "Please Try again with the correct Information",
    "re-submit",
    "Back To Recipient List",
    "Add New Recipient",
    "recipient currency",
    "Recipient name",
    "Recipient email",
    "choose a service",
    "Recipient details",
    "Delete",
    "Basic Information",
    "Nick Name",
    "change nickname",
    "Country Name",
    "Currency",
    "My Self",
    "Account Information",
    "Service Name",
    "Bank Name",
    "Edit Recipient Nickname",
    "Name",
    "Confirm Deletion",
    "Are you sure you want to delete this recipient?",
    "Recipient List",
    "add",
    "add new",
    "Add New",
    "My Account",
    "Create recipient",
    "Myself",
    "Some one else",
    "Refer & Earn Money",
    "Invite and get $",
    "Share your link",
    "Share",
    "They get",
    "A fee-free transfer up to $:amount when they sign up through you",
    "You get",
    "Instant $:amount when they deposit any amount first time",
    "invited friend",
    "See more",
    "Share Referral link",
    "Share on Facebook",
    "Share on twitter",
    "Share on Linkedin",
    "Copied:",
    "Referral User Details",
    "Back To Referral List",
    "Referral details",
    "User Name",
    "State Name",
    "Join Date",
    "Referral List",
    "Back to Refer Page",
    "Referral users",
    "Create Ticket",
    "Back to Ticket List",
    "create a new ticket",
    "Subject",
    "Money Transfer Problem",
    "Message",
    "Describe your problem...",
    "Media",
    "Ticket List",
    "Create ticket",
    "Status",
    "Last Reply",
    "Action",
    "Ticket #",
    "view",
    "ticket No.",
    "Open",
    "Answered",
    "Replied",
    "Closed",
    "View Ticket",
    "File",
    "Back To Transaction List",
    "Transaction details",
    "Transaction Details",
    "Transaction Date",
    "Transaction History",
    "All Transaction History",
    "Start Date",
    "End Date",
    "Send Money",
    "How much do you want to send?",
    "Fast and reliable international money transfer app.",
    "Amount must be at least",
    "Amount must not exceed",
    "Transfer fee IN Local:",
    "Recipient will get:",
    "Back",
    "Transfer Details",
    "Transfer details",
    "Back to Transfer List",
    "You Have Rejected for this Transfer Request",
    "Reason",
    "Resubmit",
    "Transfer Fee",
    "Send Total",
    "Exchange Rate",
    "Recipient will Get",
    "Recipients details",
    "Send to",
    "Service",
    "Transfer Status",
    "Money Transfer History",
    "Transfer History",
    "Sending money to",
    "Draft/Initiate",
    "Completed",
    "Under Review",
    "OTP",
    "Select Your verify option",
    "we will send an otp code to your email & sms both.",
    "we will send an otp code to your whats app number.",
    "transfer confirm",
    "Cancel this transfer",
    "Confirmation",
    "Are you sure you want to permanently remove this transfer?",
    "Confirm",
    "Pay Amount",
    "Back To Transfer History",
    "Wallet Payment",
    "Send money from your wallet",
    "Transfer fees (included)",
    "will get",
    "Select Gateway Currency",
    "Kindly choose the currency through which you'd like to transfer money using the gateway.",
    "confirm and continue",
    "Are you sure you want to cancel this transfer?",
    "Who do you want to send money to?",
    "All",
    "Send",
    "Payment Review",
    "Review details of your transfer",
    "Recipient Account details",
    "confirm & continue",
    "2 Step Security",
    "Two Factor Authenticator",
    "Disable Two Factor Authenticator",
    "Enable Two Factor Authenticator",
    "Google Authenticator",
    "Use Google Authenticator to Scan the QR code  or use the code",
    "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, install the Google Authenticator application on your mobile device.",
    "DOWNLOAD APP",
    "Verify Your OTP",
    "Enter Google Authenticator Code",
    "Verify that's you, to Disable 2FA",
    "Enter Your Password",
    "Verify",
    "Virtual Cards",
    "A “virtual card” is stored on your phone and can be used to pay contactless in stores or online, but has its own unique card number, expiry date, and CVC.",
    "Your virtual card request is pending.",
    "Your virtual card request is rejected by authority",
    "Resubmit Now",
    "Your virtual card request is generated please make it complete.",
    "Requested Block",
    "Valid Thru:",
    "CVV:",
    "Virtual Card",
    "Per Card Request Charge",
    "Request for get a virtual card",
    "Reason For Block",
    "Are You sure to send block request for this card ?",
    "Add Fund Confirmation",
    "Are You sure to send fund request for this card ?",
    "Confirm Card Request",
    "Back To Card List",
    "Card Request",
    "Security Pin",
    "Please enter your security PIN",
    "Request New Card",
    "info_box",
    "Request For",
    "Card Currency",
    "Apply",
    "Re Submit",
    "Re Order For",
    "Card Transactions",
    "SL.",
    "Provider",
    "Not Found",
    "Wallet Details",
    "Total balance",
    "send",
    "convert",
    "Make Default",
    "This card has been blocked",
    "This is your default wallet",
    "Search",
    "search",
    "Received",
    "Exchange Money",
    "Enter amount you want to exchange",
    "Receive wallet amount",
    "Insufficient Balance",
    "Your Account Balance is",
    "Money Request",
    "Money Request Details",
    "Back To Money Request List",
    "Money request has been sent to",
    "You have received a money request from",
    "Request Amount",
    "Request Date",
    "Recipient Information",
    "Requester Information",
    "Full Name",
    "Approve",
    "Reject",
    "Money Request has been Approved",
    "Money Request Rejected",
    "Money Request History",
    "Request History",
    "Money Request List",
    "Search by transaction_id",
    "Search by transaction id",
    "Request Money From",
    "select wallet currency",
    "Others",
    "Please empty your wallets before close the account",
    "Change 2-step verification settings",
    "Back to Settings",
    "Close your account",
    "Search Gateway",
    "Transaction Limit:",
    "Select currency",
    "Pay to crypto currency",
    "Select crypto currency",
    "Confirm & Next",
    "Gateway",
    "Date and Time",
    "Create New Password",
    "New Password",
    "Continue",
    "Forgot Password",
    "Enter Email Address",
    "Send Code",
    "Hello there, log in to continue!",
    "Remember me",
    "Dont have an account?",
    "Create account",
    "Verify your email",
    "Dont receive any code?",
    "Resend Code",
    "Hello there Sign Up to continue!",
    "Sign Up",
    "Card Transaction",
    "(Optional)",
    "1 File selected",
    "No File selected",
    "Choose File",
    "Field is required",
    "Rejected reason",
    "Your virtual card request is rejected by authority.",
    "No virtual cards available.",
    "Requested block",
    "Request For Get A Virtual Card",
    "Block Confirmation",
    "Are You sure to send block request for this card?",
    "Accounts",
    "Exchange Currency",
    "Account Currency",
    "Balance",
    "Wallet Balance",
    "Recipient Currency",
    "See All",
    "Remark",
    "Transaction Details",
    "Select Recipient Currency",
    "Money Transfer Details",
    "Review Details of Your Transfer",
    "Transfer details",
    "Send Your Money Here!",
    "You will Send",
    "Cancel This Transfer",
    "Get OTP",
    "Whatsapp Verify",
    "Enter your OTP",
    "Notification Permission",
    "Clear All",
    "No Notifications Yet",
    "Manual Payment",
    "PLEASE FOLLOW THE INSTRUCTION BELOW",
    "Payment Preview",
    "Change Password",
    "Current Password",
    "Enter Current Password",
    "Update Password",
    "Edit Profile",
    "Update Profile",
    "Joined At",
    "Theme Mode",
    "Auto",
    "On",
    "Off",
    "Identity Verification",
    "2FA Security",
    "Log Out",
    "Update Email",
    "Do you want to Log Out?",
    "Recipient Name",
    "Recipient Email",
    "Choose a service",
    "No Service Available",
    "Recipient Details",
    "Request",
    "Account Details",
    "Nickname",
    "Edit",
    "Enter name",
    "Update Name",
    "Send Money To Recipient",
    "Create Recipient",
    "Someone Else",
    "They Get",
    "You Get",
    "Wallet Exchange",
    "Enter Amount You Want To Exchange",
    "Receive Wallet Amount",
    "Return Home",
    "Wallet Transaction History",
    "Enter Subject",
    "Enter Message",
    "Browse Files",
    "Last reply:",
    "Type any text here",
    "Refresh",
    "Close Ticket",
    "Are you sure you want to close this ticket?",
    "Two Step Security",
    "Verify your OTP",
    "Enter your password",
    "Enter Code",
    "Verifying…",
    "Download App",
    "Verify Now",
    "Exchange Money From Your :currency Wallet",
    "Balance total",
    "Invite Your Friends to Join Us",
    "Name, email, country",
    "Transaction via",
    "Fund History",
    "Disable Two Factor Authenticator",
    "No Recents",
    "Refferal Users",
    "Your virtual card request is genereted please make it complete",
    "My Wallets",
    "wallet",
    "Default Wallet",
    "Last Month",
    "Current Month",
    "Statistics",
    "No Blogs Found",

];
